export const paddingStep = 24;

export const sliceStorageKey = 'slice';

export const initialData = [
  '.editorconfig',
  '.gitignore',
  '.idea/vcs.xml',
  '.prettierrc',
  'README.md',
  'bin/run',
  'bin/run.cmd',
  'package.json',
  'src/commands/benchmark.ts',
  'src/commands/play.ts',
  'src/commands/testBoard.ts',
  'src/commands/testStrategy.ts',
  'src/index.ts',
  'src/sim/Board.ts',
  'src/sim/benchmark.ts',
  'src/sim/boardRenderer.ts',
  'src/sim/entities.ts',
  'src/sim/generators/random.ts',
  'src/sim/play.ts',
  'src/sim/replay.ts',
  'src/sim/shipTests.ts',
  'src/sim/strategies/random.ts',
  'src/sim/strategies/scan.ts',
  'src/utils/errorFormatter.ts',
  'src/utils/requireUncached.ts',
  'tsconfig.json',
  'tsconfig.tsbuildinfo',
  'yarn-error.log',
  'yarn.lock',
];
